CSE/urls.py

from django.urls import path
from CSE import views
from CSE.views import StuList, Forms, StudentDetail, StudentUpdate, StudentDelete
from CSE.views import EmployeeList, EmployeeForms, EmployeeDetail, EmployeeUpdate, EmployeeDelete


app_name = 'CSE'

urlpatterns = [
    path('index', views.index, name='home'),
    path('index', views.index, name='index'),
    path('products', views.products, name='products'),
    path('service', views.service, name='service'),
    path('contacts', views.contacts, name='contacts'),
    path('basic', views.basic, name='basic'),

    # CBV
    path('List', StuList.as_view(), name='list'),
    path('forms', Forms.as_view(), name='forms'),
    path('<pk>/detail', StudentDetail.as_view(), name='detail'),
    path('<pk>/update', StudentUpdate.as_view(), name='update'),
    path('<pk>/delete', StudentDelete.as_view(), name='delete'),
    #CBV2
    path('', EmployeeList.as_view(), name='list'),
    path('forms1', EmployeeForms.as_view(), name='forms'),
    path('<pk>/detail1', EmployeeDetail.as_view(), name='detail'),
    path('<pk>/update1', EmployeeUpdate.as_view(), name='update'),
    path('<pk>/delete1', EmployeeDelete.as_view(), name='delete'),



    # FBV
    path('student', views.student, name='student'),  # Only keep one
    path('form', views.form, name='form'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

    ###GET and POST

    path('nie',views.nie, name = 'nie'),
    path('add', views.add, name = 'add'),
    path('add1', views.add1, name = 'add1'),

    # login, logout, user registration
    path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login'),
    path('logout', views.logoutuser, name = 'logout'),

]

NIE/CSE/urls.py
from django.urls import path
from CSE import views
from CSE.views import StuList, Forms, StudentDetail, StudentUpdate, StudentDelete

app_name = 'CSE'
urlpatterns = [
 path('index', views.index, name = 'index'),
path('products', views.products, name = 'products'),
path('service', views.service, name = 'service'),
path('contacts', views.contacts, name = 'contacts'),
path('basic', views.basic, name = 'basic'),
path('studentList', views.studentList, name = 'studentList'),

path('', StuList.as_view(), name = 'list'),
path('forms', Forms.as_view(), name = 'forms'),
path('<pk>/detail', StudentDetail.as_view(), name = 'detail'),
path('<pk>/update', StudentUpdate.as_view(), name = 'update'),
path('<pk>/delete', StudentDelete.as_view(), name = 'delete'),


]

NIE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CSE.urls')),
]

NIE/CSE/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=50)
    department = models.CharField(max_length=30)
    college_name = models.CharField(max_length=30)
    rollnumber = models.IntegerField()
    def __str__(self):
        return self.name

NIE/CSE/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

def products(request):
    name = 'raju'
    department = 'CSE'
    college_name = 'NIE'
    roll_number = 60145
    context = {'name': name, 'c_name': college_name, 'd_name': department, 'r_number':roll_number}
    return render(request,'products.html',  context)

def service(request):
    return render(request,'service.html')

def contacts(request):
    return render(request,'contacts.html')

def studentList(request):
    return render(request,'studentList.html')


def basic(request):
    return render(request,'basic.html')



 #FBV - List view
from CSE.models import Student
def studentList(request):
    students = Student.objects.all()
    context ={'students':students}
    return render(request, 'studentList.html', context)

#FBV 
from CSE.models import Student
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

class StuList(ListView):
    model = Student
    template_name = 'CBV/list.html'


class Forms(CreateView):
    model = Student
    fields = "__all__"
    template_name = 'CBV/forms.html'
    success_url = '/'


class StudentDetail(DetailView):
    model = Student
    template_name = 'CBV/detail.html'

class StudentUpdate(UpdateView):
    model = Student
    fields = '__all__'
    template_name = 'CBV/update.html'
    success_url = '/'

class StudentDelete(DeleteView):
    model = Student
    template_name = 'CBV/delete.html'
    success_url = '/'

templates/add.html
{% extends 'basic.html' %}

{% block content %}

<h1>Result is : {{ result }} </h1>

{% endblock %}

templates/basic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django_web development</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
   
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'CSE:index' %}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'CSE:index' %}">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:products' %}">Products</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:service' %}">Service</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:contacts' %}">Contacts</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:student' %}">FBV-Student</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:list' %}">CBV-Student</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:forms' %}">Student Apply</a>
              </li>

              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  FBV_Student
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'CSE:student' %}">FBV-List</a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:form' %}">FBV-regiration</a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:nie' %}">GET-POST Addision of two numbers</a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:register' %}">User - Registration </a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:login' %}">login </a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:logout' %}">logout </a></li>
                </ul>
              </div>

              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  CBV_Student
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'CSE:list' %}">CBV-List</a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:forms' %}">CBV-regiration</a></li>
                 
                </ul>
              </div>
              <div>
                {% if user.is_authenticated %}
                      <p>Welcome, {{ user.username }}!</p>
                {% else %}
                      <p>Welcome, Guest!</p>
                {% endif %}

              </div>
              
                          
          </div>
        </div>
      </nav>


    </nav> 

    {% block content %}

    {% endblock %}




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/contacts.html
{% extends 'basic.html' %}


{% block content %}
<h1> This is a contacts page.</h1>

{% endblock %}

templates/index.html
{% extends 'basic.html' %}

{% block content %}
<h1>Welcome to web development</h1>

{% endblock %}

templates/nie.html
{% extends 'basic.html' %}

{% block content %}
<h1>We are discussing about GET and POST requests.</h1>

GET request:
<form action = 'add'>
    Enter the first number:<input type = 'text' name='num1'><br><br>
    Enter the second number:<input type = 'text' name='num2'><br><br>
    <input type = 'submit'>
</form>

POST request:

<form action = 'add1' method = 'post'>
    {% csrf_token %}
    Enter the first number:<input type = 'text' name='num1'><br><br>
    Enter the second number:<input type = 'text' name='num2'><br><br>
    <input type = 'submit'>
</form>

{% endblock %}

templates/products.html
{% extends 'basic.html' %}

{% block content %}
<h1>This is a products page.</h1>
Name: {{name}}<br>
Department: {{d_name}}<br>
College:{{c_name}}<br>
Roll number: {{r_number}}
{% endblock %}








This is a products page.

templates/service.html

{% extends 'basic.html' %}

{% block content %}
<h1>This is a service page.</h1>

{% endblock %}